### PR TITLE
 BREAKING CHANGE: krt-v2 e2e support

### PR DESCRIPTION
**Pull request by alexrodfe**
## Why
krt-v2 support for the e2e testing suite.

## What
- Update both go and python nodes to runners V3
- NATS streams are created beforehand simulating "KRE-NATS_MANAGER" functionality
- New env config to accommodate KRT V2

### CODE REVIEW

**Comment by alexrodfe** [comment]
Please note this PR contains all changes coming from PRs kre-go, kre-py and kre-entrypoint. Which are needed to leave this PR functional, this PR is dependent on all those 3 pieces.
@JYisus @alejandrogr @dfinteligenz

**Review by dfinteligenz — APPROVED** [review]

**Review by JYisus — APPROVED** [review]

**Pull request merged**
