### PR TITLE
feat: add test on kre-py runner

### PR DESCRIPTION
**Pull request by blopezpi**
This PR add testing on the kre-py runner:
- The runner is built on docker-compose.
- The test is executed on PR and every push in all branches monitoring changes on a set of directories.

### CODE REVIEW

**Review by aacecandev — APPROVED** [review]

**Comment by aacecandev** [comment]
Habemus Test!

**Review by alpiquero — APPROVED** [review]

**Comment by alejandrogr** [comment]
This is a big improvement in the repo, good work @blopezpi !

Two things:

1. Please add a brief PR description
2. Can we separate the protobuf  upgrade to its own PR?

**Comment by blopezpi** [comment]
> This is a big improvement in the repo, good work @blopezpi !
> 
> Two things:
> 
>     1. Please add a brief PR description
> 
>     2. Can we separate the protobuf  upgrade to its own PR?

Yeah, I will separate the test from the protobuf update.

**Pull request merged**
